CREATE TABLE task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    status VARCHAR(20),
    visibility VARCHAR(20),
    created_at TIMESTAMP,
    created_by VARCHAR(255),
    modified_at TIMESTAMP,
    modified_by VARCHAR(255),
    due_date DATE,
    parent_id BIGINT,
    task_code VARCHAR(50),
    version BIGINT
);

CREATE TABLE audit_log (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    task_id BIGINT NOT NULL,
    operation VARCHAR(50) NOT NULL,         -- np. CREATED, UPDATED, DELETED
    user_id VARCHAR(255) NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    changes CLOB                              -- np. {"title":"new","description":"changed"}
);